topicos = [
    {'topico': 'covid', 'mensaje': 'avance 30%'},
    {'topico': 'covid', 'mensaje': 'avance 40%'},
    {'topico': 'covid', 'mensaje': 'avance 50%'},
    {'topico': 'gripe', 'mensaje': 'avance 20%'},
    {'topico': 'gripe', 'mensaje': 'disminuyo 10%'},
    {'topico': 'cancer', 'mensaje': 'avance 5%'},
    {'topico': 'cancer', 'mensaje': 'avance 30%'},
    {'topico': 'cancer', 'mensaje': 'avance 38%'},
    {'topico': 'sida', 'mensaje': 'disminuyo 30%'},
    {'topico': 'sida', 'mensaje': 'disminuyo 20%'},
    {'topico': 'sida', 'mensaje': 'disminuyo 10%'},
    {'topico': 'gripe', 'mensaje': 'disminuyo 10%'},
    {'topico': 'covid', 'mensaje': 'disminuyo 30%'},
    {'topico': 'covid', 'mensaje': 'disminuyo 15%'},
    {'topico': 'covid', 'mensaje': 'avance 30%'},
    {'topico': 'hidrocefalia', 'mensaje': 'avance 30%'},
    {'topico': 'hidrocefalia', 'mensaje': 'avance 60%'},
    {'topico': 'hidrocefalia', 'mensaje': 'disminuyo 30%'},
]